    receivers:
      otlp:
        protocols:
          grpc:
          http:
          
    exporters:
      otlphttp:
        endpoint: "$DT_ENDPOINT/api/v2/otlp"
        headers:
          Authorization: "Api-Token $DT_API_TOKEN"

    processors:
      batch:
        send_batch_max_size: 1000
        timeout: 30s
        send_batch_size : 800

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]